### ISSUE TITLE
.sass-cache isn't being ignored

### ISSUE THREAD

**Issue by alfredoreduarte** [lukevella/react-activity#1]
I think you missed this one: 

![screen shot 2016-04-02 at 4 10 04 pm](https://cloud.githubusercontent.com/assets/4633753/14228768/720a9836-f8ed-11e5-98f8-b424810608c9.png)

**Comment by lukevella** [comment]
Hey @alfredoreduarte it looks like `.sass-cache` is already in `.gitignore`. Are you sure that wasn't generated after running a build?
