### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by andrerpena** [lukevella/react-activity#7]
First, thank you very much for this library.

Do you have any plans to updating the "peerDependencies" to React 16? Now I get these annoying warning messages when I use yarn.

Thank you!

**Comment by andrerpena** [comment]
If I fix it, do you accept the PR?

**Comment by lukevella** [comment]
Hey @andrerpena I would have accepted a PR for sure but i think the issue you've been having is fixed in 1.1.3
