### ISSUE TITLE
Support 'animating' property

### ISSUE THREAD

**Issue by miphe** [lukevella/react-activity#8]
As activity indicators generally are temporarily rendered during an activity, a boolean property to support this would make working with the react-activity indicators smoother.

`<Dots size={20} animating={this.state.processing} />`

At times when `this.state.processing` is true/truthy the dots would render, otherwise nothing would render. This is how React Native does it with its `ActivityIndicator` component.

**Comment by lukevella** [comment]
Hi, thanks for your suggestion. You can expect to see this in an update soon.
